# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [ ]:

import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of NumPy you are running (as each library, you can use np.__version__)
np.__version__

'1.23.5'

In [ ]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])
p = np.array([0.8, 0.6, 0.4])
p

array([0.8, 0.6, 0.4])

In [ ]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements,
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])
def random_array():
    return 0.25 + np.random.random(10) * 0.75

print(random_array())


[0.74144807 0.37060543 0.92164723 0.7491259  0.84106149 0.51109281
 0.27810436 0.82121523 0.59788028 0.9980436 ]


In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here
"""
np.empty retourne un tableau de taille spécifiée sans initialiser les éléments à des valeurs particulières.
Cela permet de créer un tableau rapidement sans passer du temps à l'initialiser,
mais les éléments du tableau contiendront des valeurs indéfinies issues des résidus de la mémoire.
Il faudra donc remplir le tableau avec des valeurs valides avant de l'utiliser.
"""
empty_array = np.empty((3, 3))

print(empty_array)



[[4.66577776e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
# Mission 5 : Create an array filled with only zeros. You can choose the length of this array.
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Mission 6 : Create an array filled with 10 random integers.
inte = np.random.randint(0, 10, 10)
inte

array([9, 4, 7, 5, 3, 0, 2, 6, 9, 2])

In [ ]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.
rand = np.random.randint(0, 8, 50)
rand

array([4, 0, 6, 4, 5, 0, 0, 5, 7, 2, 4, 4, 3, 4, 6, 5, 6, 3, 2, 5, 5, 7,
       3, 4, 4, 6, 0, 2, 6, 5, 1, 5, 5, 6, 2, 3, 1, 0, 3, 7, 7, 4, 5, 5,
       0, 3, 2, 0, 0, 1])