In [ ]:
import numpy as np


Execute the cell below before starting the 1st mission.

In [ ]:
array_1 = np.array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

array_1

array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

# Mission 1

Using Numpy, how many axes `array_1` has ?




In [ ]:
print("Le nombre d'axes du array est de", array_1.ndim)

Le nombre d'axes du array est de 1


Still using Numpy, how many dimensions `array_1` has?

In [ ]:
print("La dimension du array est de", array_1.ndim)

La dimension du array est de 1


Display the first element of `array_1`

In [ ]:
print("First ele of array is", array_1[0])

First ele of array is 10


# Mission 2

Modify, using a `numpy` method, the `array_1` object to be an object that has two axes, including 1 row and 32 columns.  
Save it under the variable `array_2`.

In [ ]:
array_2 = array_1.reshape(1, 32)
array_2

array([[10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54,
        54, 35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35]])

Now, modify `array_1` into an object that has 32 rows and only 1 column.  
Save it under the variable `array_3`.

In [ ]:
array_3 = array_1.reshape(32, 1)
array_3

array([[10],
       [40],
       [45],
       [ 5],
       [66],
       [91],
       [43],
       [75],
       [40],
       [28],
       [55],
       [45],
       [31],
       [71],
       [67],
       [54],
       [54],
       [35],
       [64],
       [27],
       [12],
       [93],
       [17],
       [91],
       [50],
       [57],
       [74],
       [61],
       [86],
       [20],
       [36],
       [35]])

Access the first element of `array_2`, then of `array_3`.  
What do you notice?  
Why ?

In [ ]:
"""
Les deux tableaux, array_2 et array_3, ont des formes différentes.

- array_2 a été reshape en 1 ligne et 32 colonnes.
- array_3 a été reshape en 32 lignes et 1 colonne.

Quand nous accédons au premier élément avec array_2[0],
nous obtenons la première ligne, qui contient tous les 32 éléments,
car array_2 a une structure de 1 ligne et 32 colonnes.

Lorsque nous accédons au premier élément de array_3 avec array_3[0],
nous obtenons également la première ligne, mais dans ce cas,
la ligne contient seulement 1 élément, car array_3 a une structure de 32 lignes et 1 colonne.
"""
print("array_2 :", array_2[0])
print("array_3 :", array_3[0])


array_2 : [10 40 45  5 66 91 43 75 40 28 55 45 31 71 67 54 54 35 64 27 12 93 17 91
 50 57 74 61 86 20 36 35]
array_3 : [10]


# Mission 3

Access the value that is at index 3 of array `array_2`.  
Do it with Numpy way, then with Python way.

In [ ]:
py_ = array_2[0][3]
py_

5

Access the value which is at index 3 of array `array_3` in Numpy.

In [ ]:
np_ = array_2[:, 3]
np_

array([5])

# Mission 4

Reshape `array_1` to be a 4-row, 8-column array,
rather than a 32-element vector.  
Save your array under the variable `array_4`.

In [ ]:
array_4 = array_1.reshape(4, 8)
print(array_4)

[[10 40 45  5 66 91 43 75]
 [40 28 55 45 31 71 67 54]
 [54 35 64 27 12 93 17 91]
 [50 57 74 61 86 20 36 35]]


Access for each row, the values ​​of the columns which have the index 1 to 2 included.

In [ ]:
col = array_4[:, 1:3]
col

array([[40, 45],
       [28, 55],
       [35, 64],
       [57, 74]])

Access for rows at position 1 and 2 inclusive, the values ​​of all columns.

In [ ]:
row = array_4[1:3, :]
row

array([[40, 28, 55, 45, 31, 71, 67, 54],
       [54, 35, 64, 27, 12, 93, 17, 91]])

Access for the rows which have the index 2 to 3 inclusive, to the values ​​of the columns which have the index 3 to 5 inclusive.

In [ ]:
row_i = array_4[2:4, 3:6]
row_i

array([[27, 12, 93],
       [61, 86, 20]])

Select the first column, as well as the columns whose index is a multiple of 2.

In [ ]:
mult_2 = array_4[:, np.where(array_4[0, :] % 2 == 0)[0]]
print(mult_2)

[[10 40 66]
 [40 28 31]
 [54 35 12]
 [50 57 86]]


Select columns whose index is odd.

In [ ]:
odd = array_4[:, np.where(array_4[0, :] % 2 == 1)[0]]
print(odd)

[[45  5 91 43 75]
 [55 45 71 67 54]
 [64 27 93 17 91]
 [74 61 20 36 35]]


# Mission 5

Reshape your `array_1` vector into a 3-dimensional array.
Your 3-dimensional array should have 2 matrices, each of which has 4 rows and 4 columns.
Save your array under the variable `array_5`.

In [ ]:
array_5 = np.reshape(array_1, (2, 4, 4))
array_5

array([[[10, 40, 45,  5],
        [66, 91, 43, 75],
        [40, 28, 55, 45],
        [31, 71, 67, 54]],

       [[54, 35, 64, 27],
        [12, 93, 17, 91],
        [50, 57, 74, 61],
        [86, 20, 36, 35]]])

Use the .shape attribute to observe the number of axes for `array_5`.

In [ ]:
array_5.shape

(2, 4, 4)

Select all values ​​from the first matrix.

In [ ]:
array_5[0]

array([[10, 40, 45,  5],
       [66, 91, 43, 75],
       [40, 28, 55, 45],
       [31, 71, 67, 54]])

Access for both matrices,
to the values ​​corresponding to the rows at index 1 and to the columns that have positions 3 and 4.

In [ ]:
array_5[:, 1, 2:4]

array([[43, 75],
       [17, 91]])

Access row values ​​at positions 2 to 3,
columns at indexes 1 to 3 included for the second matrix only.

In [ ]:
array_5[1, 1:3, 1:4]

array([[93, 17, 91],
       [57, 74, 61]])


Reshape `array_5` so that we have 8 rows and 4 columns.

In [ ]:
res_ = np.reshape(array_5, (8, 4))
res_

array([[10, 40, 45,  5],
       [66, 91, 43, 75],
       [40, 28, 55, 45],
       [31, 71, 67, 54],
       [54, 35, 64, 27],
       [12, 93, 17, 91],
       [50, 57, 74, 61],
       [86, 20, 36, 35]])